services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 9432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
